#!/usr/bin/env bash
shopt -s expand_aliases
set -x
set -e

if [ "$#" -eq 0 ]; then
  echo "Usage: $0 <path to new project dir>"
  exit 1
fi

# 1. copy over the templates.
mkdir -p $1
cp -r project/* $1
cp -r project/.gitignore $1

# 2. replace values in templates
./scripts/gen_project.py $1

# 3. The project structure is complete, build docker.
cd $1

. setup.bash
proj=${1,,}
cd docker/
${proj}_docker_build

# 4. Start the git repository
cd ..
git init
